name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}} --target glsl-editor

    - name: Create zip archive
      uses: vimtor/action-zip@v1
      with:
        files: build\bin\Release
        dest: glsl_editor.zip
        
    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: glsl_editor.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update release
      uses: ncipollo/release-action@v1
      with:
        tag: 'glsl_editor.zip'
        artifacts: ${{github.workspace}}\glsl_editor.zip
        body: "Latest glsl editor executable"
        token: ${{ secrets.GITHUB_TOKEN }}
      
      
